version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.2
jobs:
  frontend:
    docker:
      - image: windmillcode/angular-tornado-capybara-log4j2:0.0.6
    parallelism: 1
    environment:
    steps:
      - setup_remote_docker:
          docker_layer_caching:  
      - browser-tools/install-browser-tools   
      - checkout    
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - npm-deps-v1-{{ checksum "/root/apps/zero/frontend/AngularAppCurrent/package.json" }}
                

      - run:  
          

          echo $PATH;
          cd ~/apps/zero/frontend/AngularAppCurrent ;
          npm install -s;   
      - save_cache:
          key: npm-deps-v1-{{ checksum "/root/project/AngularApp/package.json" }}
          paths:
            - /root/project/AngularApp/node_modules              
      - run:

          cd ~/apps/zero/frontend/AngularAppCurrent;
          npm run build;
          npx firebase deploy --project auxillary-305605 --token $FIREBASE_TOKEN;



workflows:
  version: 2.1
  e2e:     
    jobs: 
      - frontend:  
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - master      
      